### ISSUE TITLE
Error at stubs.c

### ISSUE THREAD

**Issue by mahmoodn** [dslab-epfl/cloud9#19]
Hi, in an attempt to install this software on a VM (ubuntu 14.04), I get this error
```
llvm[2]: Compiling stubs.c for Release+Asserts build (bytecode)
stubs.c:450: error: expected ‘)’ before ‘which’
stubs.c:451: error: expected ‘)’ before ‘which’
stubs.c:471: error: expected ‘)’ before ‘resource’
stubs.c:472: error: expected ‘)’ before ‘resource’
stubs.c:481: error: expected ‘)’ before ‘resource’
stubs.c:482: error: expected ‘)’ before ‘resource’
```
The software is pretty old. Have you seen this before?

**Comment by stefanbucur** [comment]
Mahmood, Cloud9 has been in maintenance mode for a while, so it may indeed not work on recent Ubuntu versions. Unless you have a strong requirement to run on 14.04, I'd suggest trying to use a VM with one of the supported versions (http://cloud9.epfl.ch/setting-up).

**Comment by mahmoodn** [comment]
I was able to fix that by including `#include <sys/resource.h>` in stubs.c
